### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by pjvds** [sdushantha/tmpsms#2]
To make tmpsms packagable for package systems like Snap, AUR, etc. releases should be tagged. Preferable with semver versioning, so you can communicate breaking changes.

**Comment by sdushantha** [comment]
Done! 👍

**Comment by pjvds** [comment]
Awesome, I've created and will maintain the [tmpssms aur package](https://aur.archlinux.org/packages/tmpsms) for Arch linux users.

Keep up the great work!

**Comment by sdushantha** [comment]
Awesome sounds great!
