### ISSUE TITLE
Installs for Alpine Linux in WSL

### ISSUE THREAD

**Issue by vuchl** [sdushantha/tmpsms#4]
This is a really cool package!

For Alpine on WSL I needed to also install a few more packages so that everything worked:
```bash
apk add curl jq fzf util-linux
```

`curl` for download obviously. `jq` and `fzf` are mendtioned in the requirements. `util-linux` to have the `column` command from https://github.com/sdushantha/tmpsms/blob/master/tmpsms#L181 working.

Regards Sebastian

**Comment by sdushantha** [comment]
Thank you for letting me know! I won't be adding `util-linux` to the dependency list because `column` tends to come with almost all popular Linux distributions such as Ubuntu, Arch Linux and Debian
