### ISSUE TITLE
Why depend on fzf?

### ISSUE THREAD

**Issue by glennj** [sdushantha/tmpsms#5]
I find it odd that you use a POSIX sh but depend on fzf.
If you write for bash, you can replace
```sh
    SELECTION=$(printf %b "$PHONE_NUMBERS" | $FZF_COMMAND)
```
with
```bash
    nums=()
    while IFS= read -r num; do
        nums+=("$num")
    done < <(printf %b "$PHONE_NUMBERS")
    PS3='Select a phone number: '
    select SELECTION in "${nums[@]}" quit; do
        if [[ $SELECTION == 'quit' ]]; then
            SELECTION=""
            break
        elif [[ $SELECTION ]]; then
            break
        fi
    done
```
That works with  bash v3.2.57  and up.

**Comment by sdushantha** [comment]
From my knowledge, using an external command does not make a script, not POSIX compliant. 
I quite like the code you have come up with for the selection of the phone numbers, but `fzf` has a nicer interface in my opinion. Let's say that you want to see US numbers only. You could simply type "US" into the prompt of `fzf` and you would only be presented with US numbers.
